name:                techne
version:             0.0.0.1
github:              "isamert/techne"
license:             BSD3
author:              "İsa Mert Gürbüz"
maintainer:          "isamert@pm.me"
copyright:           "2018 İsa Mert Gürbüz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isamert/techne#readme>

dependencies:
- base >= 4.7 && < 5
- basic-prelude >= 0.7.0
- text
- megaparsec >= 7.0.1
- parser-combinators >= 1.0.0
- haskeline >= 0.7.3
- optparse-applicative >= 0.14.3.0
- mtl >= 2.2.2
- containers >= 0.5.11.0
- HUnit >= 1.6.0.0
- uniplate >= 1.6.12
- groom >= 0.1.2.1
- directory >= 1.3.1.5
- prettyprinter >= 1.2.1
- text-icu >= 0.7.0.0

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- LambdaCase
- PatternSynonyms
- TupleSections

library:
  source-dirs: src

executables:
  techne-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - techne

tests:
  techne-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - techne
